
#macro APTABASE_APP_KEY         "A-XX-1234567890"
#macro APTABASE_APP_VERSION     "1.0.0"
#macro APTABASE_BASE_URL        ""
#macro APTABASE_IS_DEBUG        debug_mode
#macro APTABASE_MAX_BATCH_SIZE  25
#macro APTABASE_FLUSH_INTERVAL  10

